# Generated by Django 5.1.2 on 2024-10-28 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
        ('store', '0003_product_category'),
    ]

    operations = [
    ]
