# Generated by Django 5.1.2 on 2024-10-28 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_merge_0002_product_image_0003_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
