# Generated by Django 5.1.2 on 2024-10-28 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_category'),
        ('store', '0006_catory-product'),
    ]

    operations = [
    ]
